version: '4.24.2'

services:
  web:
    build:
      context: .
    ports:
      - "8001:8001"
    command: ["sh", "./start.sh"]
    volumes:
      - .:/drf_learning
    env_file:
      - .env
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres_data:


